---

- name: Launch AWS instances
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - aws

- name: Bootstrap dev instances
  hosts: tag_env_dev
  remote_user: ubuntu
  become: True
  pre_tasks:
    - name: Check bootstrapped file
      stat: path=/.bootstrapped
      ignore_errors: true
      register: bootstrapped
    - apt: update_cache=yes cache_valid_time=21600
      when: bootstrapped.stat.exists == false
  roles:
    - { role: base, when: "bootstrapped.stat.exists == false" }
#    - { role: fstab, when: "bootstrapped.stat.exists == false" }
    - { role: docker, when: "bootstrapped.stat.exists == false" }
    - { role: snmpd, when: "bootstrapped.stat.exists == false" }
    - { role: dnsmasq, when: "bootstrapped.stat.exists == false" }
  post_tasks:
    - name: Create bootstrapped file
      copy:
        content: "{{ ansible_date_time.iso8601_micro }}"
        dest: /.bootstrapped
      when: bootstrapped.stat.exists == false

- name: Launch Docker registry service
  hosts: tag_tier_ops
  become: True
  roles:
    - { role: registry, tags: ['registry'] }

- name: Launch load balancer service
  hosts: tag_tier_ops
  roles:
    - { role: loadbalancer, tags: ['loadbalancer'] }

- name: Create latency based DNS entry
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - include: ../roles/loadbalancer/tasks/update_route53.yml

- hosts: tag_jenkins_master
  become: True
  roles:
    - { role: jenkins, tags: ['jenkins'] }
