#!/bin/bash -e

if [ $1 == "-p" ]; then
    push=yes
    shift
fi

targets="$*"
modules="base python2 python3 ansible s3ql jenkins"

dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# check commit hook is installed
if [ -z "$push" ] && [ ! -f ${dir}/.git/hooks/pre-commit ]; then
    echo "Error: pre-commit hook not installed!"
    echo "Please run ${dir}/ansible/bin/install-git-hook.sh"
    exit 1
fi

has_target() {
    if [ -z "$targets" ]; then
        return 0
    fi

    for target in $targets; do
        if [ $target == $1 ]; then
            return 0;
        fi
    done

    return 1
}

export $(grep image_prefix ${dir}/build.conf)

for module in $modules; do
    if has_target $module; then
        echo "================"
        echo "Building $module"
        echo "================"
        ${dir}/${module}/build
        echo ""

        if [ ! -z "$push" ]; then
            docker push ${image_prefix}/${dir}:latest
            curl -X POST --data-urlencode 'payload={"text": "*${dir}* finished", "channel": "#devop", "username": "build-bot", "icon_emoji": ":package:"}' https://hooks.slack.com/services/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
        fi
    fi
done
