---

- name: Assure certificate dir exists
  file: path="/data/ssl/root" state=directory

- name: Copy over SSL certificates
  copy:
    content: "{{ item.value }}"
    dest: "/data/ssl/{{ item.name }}.pem"
    owner: 999
    group: 999
    mode: 0400
  with_items: "{{ certs }}"

- name: Launch MariaDB container
  docker:
    name: "{{ item.name }}"
    restart_policy: on-failure
    restart_policy_retry: 5
    image: "{{ registry_server }}/mariadb:latest"
    state: reloaded
    pull: always
    net: host
    volumes:
      - "{{ item.volume }}/{{ item.name }}/sql:/var/lib/mysql"
      - "/data/ssl:/etc/ssl/mysql:ro"
    env:
      NODE_ADDR: "{{ ansible_default_ipv4.address }}"
      HOST_PORT: "{{ item.sql_port }}"
      CLS_PORT:  "{{ item.cls_port }}"
      IST_PORT:  "{{ item.ist_port }}"
      SST_PORT:  "{{ item.sst_port }}"
      BACKEND_SERVICE: "{{ item.name }}"
  with_items: "{{ db_instances }}"

- name: Wait For Cluster Element To Come Up
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ec2_private_ip_address'] }}"
    port: "{{ item.sql_port }}"
    delay: 5
    timeout: 300
    state: started
  with_items: "{{ db_instances }}"
